### PR TITLE
fixed pca9685_servo.py example

### PR DESCRIPTION
**Pull request by jvalrog**
I copied the servo sweep example from CircuitPython-Motor as it's the same example but that one has the delays in place.

The code was tested in a raspberry pi.

### CODE REVIEW

**Comment by jvalrog** [comment]
So apparently pylint don't like variable names (it thinks they are constants). But this is the actual file from the Motor library, so it must fail there too.

**Comment by dherrada** [comment]
@jvalrog Hey. So basically what you're gonna want to do is take the line:
```
from adafruit_motor import servo
```
(line 12)
and cut it and paste it above:
```
from adafruit_pca9685 import PCA9685
```
(line 11)

**Comment by jvalrog** [comment]
@dherrada fixed

**Comment by dherrada** [comment]
@ladyada Ok this is passing. I don't have the hardware to test

**Comment by jerryneedell** [comment]
I ran this on a Feather M4 -- sever did its sweep.

**Comment by jposada202020** [comment]
@dherrada could we merged now this is tested.  let me know thanks..

**Comment by jposada202020** [comment]
:) thanks @dherrada and @jerryneedell

**Comment by dherrada** [comment]
Thank you!

**Pull request merged**
