### PR TITLE
Changed the default address from0x60 to 0x40

### PR DESCRIPTION
**Pull request by mrmcwethy**
Change two .py files.  motor.py and stepper.py.  Note there is not docu for stepper.py

### CODE REVIEW

**Comment by tannewt** [comment]
Thank you @mrmcwethy!

**Comment by ladyada** [comment]
@tdicola please verify this does not affect the respective guides for servo/motorwing!

**Comment by mrmcwethy** [comment]
After taking a close look these classes, I realized that DCMotor and Stepper classes are really tied to specific board designs.  They have nice generic names, but they aren't really generic since that are tied to a board design that might change in the future.  I think there are al least three Adafruit boards that use the PCA9685 chip.  I think we need to change these classes to have a base class (generic) and then add board specific classes.  This would clear up the problem of the default i2c address (e.g., 0x40 vs. 0x60) AND the board specific chip-pin assignments. @tdicola what do you think?

**Comment by mrmcwethy** [comment]
After taking a close look these classes, I realized that DCMotor and Stepper classes are tied to specific feather boards. They have nice generic names, but they aren't really generic since that are tied to those boards.


There are at least three Adafruit boards that use the PCA9685 chip:


8-Channel PWM or Servo FeatherWing Add-on For All Feather Boards,
DC Motor + Stepper FeatherWing Add-on For All Feather Boards, and
Adafruit Motor/Stepper/Servo Shield for Arduino v2 Kit - v2.3. 


So I think i have broken the Learn document concerning Motors and Steppers.  The Servo/PWM Feather board uses 0x40 by default, but the other two boards use 0x60 by default.  By changing the default address, Tony's Learn documents will fail.  Maybe we should back out my changes and update the CircuitPython documents to clarify the library's board compatibility.  I feel bad about this, since LadyAda got involved.

**Pull request merged**
